### ISSUE TITLE
Training for MS-COCO to M3FD problem

### ISSUE THREAD

**Issue by kiranadam** [ganlumomo/thermal-uda-cls#2]
(thermal-uda-cls) kiranadam@kiranadam:~/thermal-uda-cls$ python core/main.py  --tgt_cat m3fd --n_classes 6  --batch_size 8 --epochs 30  --device cuda:0 --logdir outputs/m3fd --self_train
2023-06-06 15:15:57,551 - Namespace(batch_size=8, betas=(0.5, 0.999), d_lr=0.001, device='cuda:0', epochs=30, in_channels=3, lam=0.25, logdir='outputs/m3fd', lr=0.0001, message='altinel', n_classes=6, n_workers=4, num_val=6, self_train=True, slope=0.2, src_cat='mscoco', t_lr=1e-05, tgt_cat='m3fd', thr=0.9, thr_domain=0.87, trained='', wandb=False, weight_decay=2.5e-05)
Traceback (most recent call last):
  File "core/main.py", line 153, in <module>
    run(args)
  File "core/main.py", line 41, in run
    target_conf_train_loader = get_m3fd_from_list_wdomain(dataset_root, args.batch_size, train=True)
  File "/home/kiranadam/thermal-uda-cls/utils/altutils.py", line 335, in get_m3fd_from_list_wdomain
    m3fd_dataset = ImageFileListWeightDomain(root=dataset_root, imageFolder='uda_data/m3fd/train', flist=os.path.join(dataset_root, 'uda_data/m3fd', 'pseudo_labels_m3fd.txt'),
  File "/home/kiranadam/thermal-uda-cls/utils/imageFileListWeightDomain.py", line 29, in __init__
    self.imlist, self.weights = flist_reader(flist)		
  File "/home/kiranadam/thermal-uda-cls/utils/imageFileListWeightDomain.py", line 16, in default_flist_reader
    with open(flist, 'r') as rf:
FileNotFoundError: [Errno 2] No such file or directory: './dataset_dir/uda_data/m3fd/pseudo_labels_m3fd.txt'

I could not find pseudo_labels_m3fd.txt' and no proper doumentation

**Comment by connorlee77** [comment]
The weights are assigned per class, and inverted so that you can oversample a minor class, i.e. 
```
weight[class] = num_samples / class_count[class]
```
